### PR TITLE
Replace Travis with GitHub actions

### PR DESCRIPTION
**Pull request by RealOrangeOne**

### CODE REVIEW

**Comment by j4mie** [comment]
The Travis build matrix runs on Django 1.8, 1.11, 2.0, 2.1 and 2.2 currently.

We should probably take the opportunity to refresh this to test on currently support versions of Django and Python.

**Comment by RealOrangeOne** [comment]
This is already done in this PR, see diff:

https://github.com/dabapps/django-zen-queries/pull/26/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR12

**Comment by j4mie** [comment]
> This is already done in this PR, see diff:
> 
> https://github.com/dabapps/django-zen-queries/pull/26/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR12

It's still just running against Django 2.2 though?

**Review by j4mie — APPROVED** [review]
😎

**Pull request merged**
